site_name: NOTES
site_url: https://aashritha014.github.io/DBMS-Notes/
site_description: Comprehensive notes on Database Management Systems (DBMS) covering key concepts, theories, and practical applications.
site_author: S.Aashritha 


nav:

  - DBMS:
      - Overview: dbms.md
      - Unit 1: unit1.md
      - Unit 2: unit2.md
      - Unit 3: unit3.md
      - Unit 4: unit4.md
      - Unit 5: unit5.md
  
  - OS: 
      - Overview: os.md
      - Unit 1: os_unit1.md
      - Unit 2: os_unit2.md
      - Unit 3: os_unit3.md
      - Unit 4: os_unit4.md
      - Unit 5: os_unit5.md

  - OS LAB: 
      - Overview: oslab.md
      - Unix System Calls: program1.md
      - Multithread Concepts: program2.md
      - CPU Scheduling Algorithms: program3.md
      - Shared Memory and IPC: program4.md
      - Dining Philosopher Problem: program5.md
      - Producer-Consumer Problem: program6.md
      - Readers-Writers Problem: program7.md
      - Deadlock Detection: program8.md
      - Banker's Algorithm: program9.md
      - Page Replacement Algorithms (FIFO): program10.md
      - Page Replacement Algorithms (LRU & LFU): program11.md
      - Disk Scheduling (FCFS): program12.md
      -  Disk Scheduling (SSTF): program13.md
      

  - About Me: about.md
  

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggestions
    - toc.integrated
    - content.code.annotate
    - content.code.copy
    - content.tabs.links
    - header.autohide
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - search.share
    - announcement.bar
    - content.footer   # only this for custom footer


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aashritha014
      name: GitHub
  # Removed default copyright

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
  - def_list
  - footnotes 
